### ISSUE TITLE
Room Error after install Update

### ISSUE THREAD

**Issue by clipse2004** [benleb/ad-automoli#82] opened 2021-07-27 10:08 UTC
😩 **Describe the issue/bug**
After Installing the Update i got "Room" Error see above, reinstalling 11.0 -> all works
😒 **Expected behavior**

🎛️ **Configuration**
```yaml
esszimmer:
  module: automoli
  class: AutoMoLi
  room: esszimmer
  disable_switch_entities:
    - input_boolean.automoli_deaktivieren
  disable_switch_states: "off"
  dim:
    method: transition
    seconds_before: 5
  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - { starttime: "sunrise", name: morning, light: 35, delay: 45 }
    - { starttime: "07:30", name: day, light: 100, delay: 60 }
    - { starttime: "sunset-22:30", name: evening, light: 65, delay: 75 }
    - { starttime: "22:30", name: night, light: 50, delay: 45 }

  humidity:
    - sensor.netatmo_home_wetter_station_modul_esszimmer_humidity
  illuminance:
    - sensor.bewegungsmelder_hue_esszimmer_light_level
  illuminance_threshold: 5
  lights:
    - light.stehlampe_hue_signe_esszimmer
  motion:
    - binary_sensor.bewegungsmelder_hue_esszimmer_motion
    - binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
```
🧠 **System**
 - AppDaemon: **4.0.5**
   -  running mode: **hassio-plugin]**
 - Home-Assistant: **[e.g. 0.118.3, 0.119.0b0]**
   -  running mode: **hassio**
 - Python: ** 3.8.6**

🗒️ **Logs** 

```log
2021-07-27 12:03:57.111656 INFO schlafzimmer:  
2021-07-27 12:03:57.112539 WARNING schlafzimmer: ------------------------------------------------------------
2021-07-27 12:03:57.113412 WARNING schlafzimmer: Unexpected error running initialize() for schlafzimmer
2021-07-27 12:03:57.114113 WARNING schlafzimmer: ------------------------------------------------------------
2021-07-27 12:03:57.115598 WARNING schlafzimmer: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 215, in initialize
    self.lg("")
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 163, in lg
    name=self.room.name.capitalize(),  # type:ignore
AttributeError: 'AutoMoLi' object has no attribute 'room'
2021-07-27 12:03:57.116220 WARNING schlafzimmer: ------------------------------------------------------------
```

🧁 **Additional context**

**Comment by benleb** [comment] 2021-07-29 18:58
Already fixed in master, see https://github.com/benleb/ad-automoli/issues/81

**Closed by benleb** 2021-07-29 18:58 UTC

**Comment by clipse2004** [comment] 2021-07-29 20:26
Not for me, now i get this Error 
`AppDaemon: Initializing app badezimmer using class AutoMoLi from module automoli
2021-07-29 22:24:26.082421 INFO AppDaemon: Initializing app küche using class AutoMoLi from module automoli
2021-07-29 22:24:26.093084 INFO badezimmer:  
2021-07-29 22:24:26.097260 INFO badezimmer:   hey, what about trying Python >= 3.9‽ 🤪
2021-07-29 22:24:26.101273 INFO badezimmer:  
2021-07-29 22:24:26.205062 WARNING badezimmer: ------------------------------------------------------------
2021-07-29 22:24:26.205755 WARNING badezimmer: Unexpected error in worker for App badezimmer:
2021-07-29 22:24:26.206479 WARNING badezimmer: Worker Ags: {}
2021-07-29 22:24:26.207141 WARNING badezimmer: ------------------------------------------------------------
2021-07-29 22:24:26.208108 WARNING badezimmer: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 358, in initialize
    self.room = Room(
TypeError: __init__() got an unexpected keyword argument 'room_lights'
2021-07-29 22:24:26.208692 WARNING badezimmer: ------------------------------------------------------------
2021-07-29 22:24:26.213064 INFO küche:  
2021-07-29 22:24:26.216999 INFO küche:   hey, what about trying Python >= 3.9‽ 🤪
2021-07-29 22:24:26.220936 INFO küche:  
2021-07-29 22:24:26.324631 WARNING küche: ------------------------------------------------------------
2021-07-29 22:24:26.325325 WARNING küche: Unexpected error in worker for App küche:
2021-07-29 22:24:26.326040 WARNING küche: Worker Ags: {}
2021-07-29 22:24:26.326685 WARNING küche: ------------------------------------------------------------
2021-07-29 22:24:26.327851 WARNING küche: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 358, in initialize
    self.room = Room(
TypeError: __init__() got an unexpected keyword argument 'room_lights'
2021-07-29 22:24:26.328415 WARNING küche: ------------------------------------------------------------ `

**Comment by benleb** [comment] 2021-07-29 20:43
oh sorry! Looks like you are somehow running an old version of [adutils](github.com/benleb/adutils), a dependency of AutoMoLi which should be installed automatically like shown in the screen below. (fresh docker container on  first start)
![image](https://user-images.githubusercontent.com/512997/127562541-38366ba9-a3fe-48a2-9f48-35f8bfa8d787.png)

can you check which version of adutils you are running? and if its not adutils-0.6.2, upgrade to it and try again?

and do you have an idea why auto-install does not work in your setup? seems like you also use docker for appdaemon right? do you have some "uncommon" setup or anything which could cause this? 

I will try to reproduce this with python3.8 meanwhile....

**Comment by clipse2004** [comment] 2021-07-29 21:36
I use Hassio as my system and have installed Appdaemon via Supervisor. That should then run via docker or? ;) 
aputils I have now times as a Python package pull the current (before I had Appdaemon there nothing specified)
So with version 11 (which is now running again) everything worked fine.
Be but briefly so kind and look at my Config, I could not discover any error now :/ 
Thanks for your help!

`
esszimmer:
  module: automoli
  class: AutoMoLi
  room: esszimmer
  disable_switch_entities:
    - input_boolean.automoli_deaktivieren
  disable_switch_states: "off"
  dim:
    method: transition
    seconds_before: 5
  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - { starttime: "sunrise", name: morning, light: 35, delay: 45 }
    - { starttime: "07:30", name: day, light: 100, delay: 60 }
    - { starttime: "sunset-22:30", name: evening, light: 65, delay: 75 }
    - { starttime: "22:30", name: night, light: 50, delay: 45 }
    - { starttime: "00:30", name: more_night, light: 35, delay: 30 }
    - { starttime: "03:00", name: dark_night, light: 35, delay: 20 }

  humidity: sensor.netatmo_home_wetter_station_modul_esszimmer_humidity
    
  illuminance: sensor.bewegungsmelder_hue_esszimmer_light_level
  illuminance_threshold: 5
  
  lights: 
    - light.stehlampe_hue_signe_esszimmer
    
  motion:
    - binary_sensor.bewegungsmelder_hue_esszimmer_motion
    - binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone
    

badezimmer:
  module: automoli
  class: AutoMoLi
  room: badezimmer
  dim:
    method: transition
    seconds_before: 5
  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - { starttime: "sunrise", name: morning, light: 30 }
    - { starttime: "07:30", name: day, light: 100, delay: 60 }
    - { starttime: "20:30", name: evening, light: 50, delay: 75 }
    - { starttime: "22:30", name: night, light: 20, delay: 45 }
    - { starttime: "00:30", name: more_night, light: 15, delay: 30 }
    - { starttime: "03:00", name: dark_night, light: 15, delay: 20 }
 
  humidity: sensor.netatmo_home_wetter_station_modul_badezimmer_humidity
  humidity_threshold: 70
  
  illuminance: sensor.hue_motion_sensor_1_light_level
  illuminance_threshold: 5
  
  lights: 
    - light.spiegellampe_hue
  
  motion:
    - binary_sensor.hue_motion_sensor_1_motion
    - binary_sensor.lumi_lumi_sensor_motion_aq2_ca0d1104_ias_zone
    - binary_sensor.lumi_lumi_sensor_motion_aq2_5d321104_ias_zone
    

küche:
  module: automoli
  class: AutoMoLi
  room: küche
  dim:
    method: transition
    seconds_before: 5
  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - { starttime: "05:30", name: morning, light: 30, delay: 45 }
    - { starttime: "07:30", name: day, light: 100, delay: 60 }
    - { starttime: "20:30", name: evening, light: 75, delay: 75 }
    - { starttime: "22:30", name: night, light: 50, delay: 45 }
    - { starttime: "00:30", name: more_night, light: 25, delay: 30 }
    - { starttime: "03:00", name: dark_night, light: 25, delay: 20 }

  illuminance: sensor.bewegungsmelder_hue_kuche_light_level
  illuminance_threshold: 4
  
  room_lights: 
    - light.hue_kuche
  
  motion:
    - binary_sensor.bewegungsmelder_hue_kuche_motion
    

schlafzimmer:
  module: automoli
  class: AutoMoLi
  room: schlafzimmer
  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - { starttime: "13:30", name: day, light: 100, delay: 75 }
    - { starttime: "20:30", name: evening, light: 100, delay: 45 }
    - { starttime: "22:00", name: night, light: 0 }

  humidity: sensor.netatmo_home_wetter_station_modul_schlafzimmer_humidity
  
  illuminance: sensor.hue_bewegungsmelder_schlafzimmer_light_level
  illuminance_threshold: 4
 
  room_lights: 
    - light.dimmer_schlafzimmer
  
  motion:
    - binary_sensor.hue_bewegungsmelder_schlafzimmer_motion
    - binary_sensor.lumi_lumi_sensor_motion_aq2_5032f403_ias_zone `
