### ISSUE TITLE
Lights do not turnOff direct when illuminate is more than set value

### ISSUE THREAD

**Issue by jompa68** [benleb/ad-automoli#27] opened 2020-02-19 17:44 UTC

**Comment by jompa68** [comment] 2020-02-21 11:12
any comments on this? Have I configure it wrong?

**Comment by samnewman86** [comment] 2020-02-23 05:29
Can you describe clearer what the problem is please?

**Comment by jompa68** [comment] 2020-02-23 06:15
If illumination value is more then threshold it should turnOff lights direct. But it does not.
 ```
 illuminance: 
    - sensor.kok_772_0_2_775
  illuminance_threshold: 12
```

**Comment by samnewman86** [comment] 2020-02-23 10:11
Ah I see what you mean now, you want the lights to turn off if the curtains open and it get lighter.
Thats not a function of this program, if the illuminance is above the threshold the lights will not turn on, but if they are already turned on they wont turn off when it gets brighter.
Think about the logic here, it wouldnt work
Its dark and theres motion>light turns on>sensor illuminated by artificial light>light turns back off
The sensor doesnt know if its being illuminated by artificial or natural light, so it would cause the lights to turn back off all the time even if without artificial light the room would be dark.

**Comment by benleb** [comment] 2020-02-29 14:03
Thanks for explaining @samnewman86! Closing this as it seems "solved" in a way

**Closed by benleb** 2020-02-29 14:03 UTC

**Comment by samnewman86** [comment] 2020-02-29 14:18
I have seen some proprietary systems that have a illuminance sensor built into each light, however they must use some kind of frequency filtering to differentiate between daylight and artificial light
